package sandbox;

/*Generated by MPS */


public class map_App {

  public static void main(String[] args) {
    System.out.println("// Code Generated by ArduinoML\n");

    System.out.println("// Structural concepts");
    System.out.println("void setup() {");
    System.out.println("  pinMode(" + 38 + ", OUTPUT);");
    System.out.println("  pinMode(" + 42 + ", INPUT);");
    System.out.println("}");

    System.out.println("\n// Behavioral concepts");
    System.out.println("long time = 0; long debounce = 200;\n");

    System.out.println("void state_" + "init" + "() {");
    System.out.println("  digitalWrite(" + 38 + ", " + "HIGH" + ");");
    System.out.println("  boolean guard =  millis() - time > debounce;");
    System.out.println("  if (digitalRead(" + 42 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("    time = millis(); state_" + "wow" + "(); ");
    System.out.println("  } else { state_" + "init" + "(); }");
    System.out.println("}\n");
    System.out.println("void state_" + "wow" + "() {");
    System.out.println("  digitalWrite(" + 38 + ", " + "LOW" + ");");
    System.out.println("  boolean guard =  millis() - time > debounce;");
    System.out.println("  if (digitalRead(" + 42 + ") == " + "LOW" + " && guard ) {");
    System.out.println("    time = millis(); state_" + "init" + "(); ");
    System.out.println("  } else { state_" + "wow" + "(); }");
    System.out.println("}\n");

    System.out.println("\nvoid loop() { state_" + "init" + "(); } // Entering init state\n");
  }
}
