package BGnamiCode.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum DIRECTION {
  UP("UP", 0),
  RIGHT("RIGHT", 1),
  DOWN("DOWN", 2),
  LEFT("LEFT", 3);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  DIRECTION(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<DIRECTION> getConstants() {
    List<DIRECTION> list = ListSequence.fromList(new LinkedList<DIRECTION>());
    ListSequence.fromList(list).addElement(DIRECTION.UP);
    ListSequence.fromList(list).addElement(DIRECTION.RIGHT);
    ListSequence.fromList(list).addElement(DIRECTION.DOWN);
    ListSequence.fromList(list).addElement(DIRECTION.LEFT);
    return list;
  }
  public static DIRECTION getDefault() {
    return null;
  }
  public static DIRECTION parseValue(String value) {
    if (value == null) {
      return DIRECTION.getDefault();
    }
    if (value.equals(DIRECTION.UP.getValueAsString())) {
      return DIRECTION.UP;
    }
    if (value.equals(DIRECTION.RIGHT.getValueAsString())) {
      return DIRECTION.RIGHT;
    }
    if (value.equals(DIRECTION.DOWN.getValueAsString())) {
      return DIRECTION.DOWN;
    }
    if (value.equals(DIRECTION.LEFT.getValueAsString())) {
      return DIRECTION.LEFT;
    }
    return DIRECTION.getDefault();
  }
}
