package BGnamiCode.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cells.EditorCell_Indent;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.openapi.editor.menus.transformation.SNodeLocation;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.impl.cellActions.CellAction_DeleteSmart;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.OldNewCompositeSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class BgnamiApp_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_iwhuv3_a(editorContext, node);
  }
  private EditorCell createCollection_iwhuv3_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_iwhuv3_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createCollection_iwhuv3_a0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_iwhuv3_b0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_iwhuv3_c0(editorContext, node));
    return editorCell;
  }
  private EditorCell createCollection_iwhuv3_a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_iwhuv3_a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_iwhuv3_a0a(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_iwhuv3_a0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "BGnami app {");
    editorCell.setCellId("Constant_iwhuv3_a0a");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createCollection_iwhuv3_b0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_iwhuv3_b0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_iwhuv3_a1a(editorContext, node));
    return editorCell;
  }
  private EditorCell createCollection_iwhuv3_a1a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_iwhuv3_a1a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createIndentCell_iwhuv3_a0b0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_iwhuv3_b0b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_iwhuv3_c0b0(editorContext, node));
    return editorCell;
  }
  private EditorCell createIndentCell_iwhuv3_a0b0(EditorContext editorContext, SNode node) {
    EditorCell_Indent editorCell = new EditorCell_Indent(editorContext, node);
    return editorCell;
  }
  private EditorCell createRefNode_iwhuv3_b0b0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new BgnamiApp_Editor.codeSingleRoleHandler_iwhuv3_b0b0(node, MetaAdapterFactory.getContainmentLink(0xca6f6e4e20be476aL, 0xbf2e14a6b4d9e674L, 0x30f63d29e61b1e5fL, 0x30f63d29e61c1437L, "code"), editorContext);
    return provider.createCell();
  }
  private class codeSingleRoleHandler_iwhuv3_b0b0 extends SingleRoleCellProvider {
    public codeSingleRoleHandler_iwhuv3_b0b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      myEditorContext.getCellFactory().pushCellContext();
      myEditorContext.getCellFactory().setNodeLocation(new SNodeLocation.FromNode(child));
      try {
        EditorCell editorCell = super.createChildCell(child);
        editorCell.setAction(CellActionType.DELETE, new CellAction_DeleteSmart(myOwnerNode, MetaAdapterFactory.getContainmentLink(0xca6f6e4e20be476aL, 0xbf2e14a6b4d9e674L, 0x30f63d29e61b1e5fL, 0x30f63d29e61c1437L, "code"), child));
        editorCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteSmart(myOwnerNode, MetaAdapterFactory.getContainmentLink(0xca6f6e4e20be476aL, 0xbf2e14a6b4d9e674L, 0x30f63d29e61b1e5fL, 0x30f63d29e61c1437L, "code"), child));
        installCellInfo(child, editorCell);
        return editorCell;
      } finally {
        myEditorContext.getCellFactory().popCellContext();
      }
    }

    protected boolean isCompatibilityMode() {
      return false;
    }

    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new OldNewCompositeSubstituteInfo(myEditorContext, new SChildSubstituteInfo(editorCell, myOwnerNode, MetaAdapterFactory.getContainmentLink(0xca6f6e4e20be476aL, 0xbf2e14a6b4d9e674L, 0x30f63d29e61b1e5fL, 0x30f63d29e61c1437L, "code"), child), new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext)));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("code");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      myEditorContext.getCellFactory().pushCellContext();
      myEditorContext.getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(myOwnerNode, MetaAdapterFactory.getContainmentLink(0xca6f6e4e20be476aL, 0xbf2e14a6b4d9e674L, 0x30f63d29e61b1e5fL, 0x30f63d29e61c1437L, "code")));
      try {
        EditorCell editorCell = super.createEmptyCell();
        editorCell.setCellId("empty_code");
        installCellInfo(null, editorCell);
        return editorCell;
      } finally {
        myEditorContext.getCellFactory().popCellContext();
      }
    }
    protected String getNoTargetText() {
      return "<no code>";
    }
  }
  private EditorCell createConstant_iwhuv3_c0b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "PUSH");
    editorCell.setCellId("Constant_iwhuv3_c0b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createCollection_iwhuv3_c0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_iwhuv3_c0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_iwhuv3_a2a(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_iwhuv3_a2a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_iwhuv3_a2a");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
